// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

type Generatedimage struct {
	ID          int32
	Imageurl    string
	Jobid       string
	Imagestatus string
	Useremail   string
}
