// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"time"
)

type User struct {
	ID           int32
	Passwordhash string
	Subscribed   bool
	Createdat    time.Time
	Email        string
}

type Usersprofile struct {
	ID          int32
	Fullname    string
	Email       string
	Useraddress string
	Postcode    string
}
