-- +goose Up
ALTER TABLE Users DROP COLUMN username;
ALTER TABLE Users ADD COLUMN email VARCHAR(255) NOT NULL UNIQUE;

-- +goose Down
ALTER TABLE Users ADD COLUMN username VARCHAR(255) NOT NULL UNIQUE;
ALTER TABLE Users DROP COLUMN email;